import { FormEvent, useState } from 'react'
const initial = { name: '', phone: '', email: '', brand: '', model: '', year: '', service: '', message: '', privacy: false }
export function InquiryForm() {
  const [values, setValues] = useState(initial); const [submitted, setSubmitted] = useState(false)
  const update = (key: keyof typeof initial, value: string | boolean) => setValues(current => ({ ...current, [key]: value }))
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!values.privacy) return; /* Backend or e-mail service integration belongs here. */ setSubmitted(true); setValues(initial) }
  if (submitted) return <div className="form-success" role="status"><span>✓</span><h3>Projektanfrage erfasst.</h3><p>Vielen Dank. Wir melden uns zur gemeinsamen Besprechung Ihres Fahrzeugprojekts.</p><button className="text-button" onClick={() => setSubmitted(false)}>Weitere Anfrage senden →</button></div>
  return <form className="inquiry-form" onSubmit={submit}>
    <label>Name<input required value={values.name} onChange={e => update('name', e.target.value)} /></label><label>Telefonnummer<input required type="tel" value={values.phone} onChange={e => update('phone', e.target.value)} /></label><label>E-Mail<input required type="email" value={values.email} onChange={e => update('email', e.target.value)} /></label><label>Fahrzeugmarke<input required value={values.brand} onChange={e => update('brand', e.target.value)} /></label><label>Modell<input required value={values.model} onChange={e => update('model', e.target.value)} /></label><label>Baujahr<input required inputMode="numeric" value={values.year} onChange={e => update('year', e.target.value)} /></label><label className="form-wide">Gewünschte Leistung<select required value={values.service} onChange={e => update('service', e.target.value)}><option value="" disabled>Bitte auswählen</option><option>Wartung & Inspektion</option><option>Reparatur & Diagnose</option><option>Teilrestaurierung</option><option>Vollrestaurierung</option><option>Technische Optimierung</option></select></label><label className="form-wide">Nachricht<textarea required rows={4} value={values.message} onChange={e => update('message', e.target.value)} /></label><label className="privacy form-wide"><input required type="checkbox" checked={values.privacy} onChange={e => update('privacy', e.target.checked)} /><span>Ich stimme der Verarbeitung meiner Angaben zur Bearbeitung dieser Anfrage zu.</span></label><button className="button button-red form-wide" type="submit">Projekt anfragen <b>↗</b></button>
  </form>
}
