import { Header } from './components/Header'
import { MustangCarCanvas } from './components/three/MustangCarCanvas'
import { InquiryForm } from './components/InquiryForm'
import { siteConfig } from './config/siteConfig'

function App() {
  return <><Header /><main>
    <section id="start" className="hero"><div className="hero-sticky"><div className="hero-noise" /><div className="hero-content"><p className="eyebrow"><span /> INDEPENDENT US CAR SPECIALISTS</p><h1>AMERICAN<br /><em>LEGENDS.</em><br />GERMAN PRECISION.</h1><p className="hero-copy">Spezialisierte Wartung, Reparatur und Restaurierung klassischer Chevrolet-, Cadillac- und Corvette-Modelle.</p><div className="hero-actions"><a className="button button-red" href="#kontakt">{siteConfig.primaryCta} <b>↗</b></a><a className="button button-line" href="#werkstatt">Werkstatt entdecken <b>↓</b></a></div></div><div className="hero-brand"><img src="/brand/workshop-logo.png" alt="DEEP CAGE US Car Tuning & Restorations" /></div><MustangCarCanvas /><a className="scroll-cue" href="#leistungen"><span /> Scroll to explore</a></div></section>
    <section id="fahrzeuge" className="brands section"><p className="eyebrow">01 / MARKENKOMPETENZ</p><div className="section-intro"><h2>BUILT FOR<br /><em>THE LONG RUN.</em></h2><p>Wir sprechen die Sprache amerikanischer Fahrzeugtechnik – vom großvolumigen V8 bis zur feinen Chromlinie. Für Fahrzeuge, die mehr als Fortbewegung sind.</p></div><div className="brand-list">{siteConfig.brands.map((brand, index) => <div key={brand}><span>0{index + 1}</span><strong>{brand}</strong><i>↗</i></div>)}</div></section>
    <section id="leistungen" className="services section"><div className="technical-backdrop">SERVICE<br />DEPARTMENT</div><p className="eyebrow">02 / LEISTUNGEN</p><div className="section-intro"><h2>PRÄZISION BIS<br /><em>INS DETAIL.</em></h2><p>Als US-Oldtimer Werkstatt verbinden wir fundierte Diagnose mit handwerklicher Konsequenz. Jeder Arbeitsschritt folgt einem klaren technischen Protokoll.</p></div><div className="service-list">{siteConfig.services.map(([num, title, copy]) => <article key={num}><span>{num}</span><h3>{title}</h3><p>{copy}</p><i>→</i></article>)}</div></section>
    <section id="restaurierung" className="process section"><p className="eyebrow">03 / RESTORATION PROTOCOL</p><div className="section-intro"><h2>VON SUBSTANZ<br />ZU <em>STÄRKE.</em></h2><p>Eine US-Car Restaurierung braucht einen Plan – und den Respekt, ihn in jeder Phase einzuhalten.</p></div><ol>{siteConfig.process.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong><i /></li>)}</ol></section>
    <section id="werkstatt" className="philosophy"><div className="philosophy-seal">DC<br /><span>V8</span></div><div><p className="eyebrow">04 / UNSERE HALTUNG</p><h2>WIR REPARIEREN<br />NICHT NUR FAHRZEUGE.<br /><em>WIR BEWAHREN<br />GESCHICHTE.</em></h2><p>Amerikanische Klassiker haben Charakter, Patina und eine eigene technische Wahrheit. Wir erhalten genau das – mit sauberer Arbeit, klarer Kommunikation und einem Anspruch, der über die nächste Ausfahrt hinausgeht.</p></div></section>
    <section id="kontakt" className="contact section"><p className="eyebrow">05 / FAHRZEUGANFRAGE</p><div className="contact-grid"><div><h2>IHR PROJEKT.<br /><em>UNSER NÄCHSTER<br />STANDARD.</em></h2><p>Erzählen Sie uns von Ihrem Fahrzeug. Wir prüfen gemeinsam, was es braucht – und welcher Weg dafür der richtige ist.</p><dl><div><dt>ERREICHBARKEIT</dt><dd>{siteConfig.hours}</dd></div><div><dt>KONTAKT</dt><dd>{siteConfig.phone}<br />{siteConfig.email}</dd></div><div><dt>STANDORT</dt><dd>{siteConfig.address}</dd></div></dl></div><InquiryForm /></div></section>
    <section className="final-cta"><p className="eyebrow">DEEP CAGE / US CAR TUNING & RESTORATIONS</p><h2>YOUR CLASSIC DESERVES<br /><em>MORE THAN A STANDARD<br />WORKSHOP.</em></h2><a className="button button-light" href="#kontakt">Jetzt Fahrzeugprojekt besprechen <b>↗</b></a></section>
  </main><footer><img src="/brand/workshop-logo.png" alt="DEEP CAGE US Car Tuning & Restorations" /><p>© {new Date().getFullYear()} DEEP CAGE. KLASSISCHE AMERIKANISCHE FAHRZEUGE.<br /><a href="https://sketchfab.com/3d-models/ford-mustang-john-bowe-1969-0e81350de30a4ba9b7255cdadb05988b" target="_blank" rel="noreferrer">Ford Mustang John Bowe 1969 · CC BY 4.0</a></p><a href="#start">Nach oben ↑</a></footer></>
}
export default App
